const express= require('express');
const UsuarioController = require('../controllers/UsuarioController');
const router=express.Router();
router.post('/guardar_usuario',UsuarioController.save);
router.get('/listar_usuarios',UsuarioController.get_usuarios);
router.get('/buscar_usuario/:id',UsuarioController.get_usuario_por_id);
router.post('/registrouser',UsuarioController.registro);
router.get('/registrouser',UsuarioController.renderRegistro);
router.post('/iniciouser',UsuarioController.inicio);
router.get('/iniciouser',UsuarioController.renderInicio);
router.delete('/eliminar_usuario/:id',UsuarioController.delete_usuario);
router.put('/actualizar_usuario/:id',UsuarioController.update_usuario);
module.exports=router;